### ISSUE TITLE
ember-cli-dialog does not load correctly... ember-template-compiler.js needed

### ISSUE THREAD

**Issue by josefguenther** [wheely/ember-dialog#37]
Disclaimer: I am posting this issue here becaus the project `ember-cli-dialog` does not have an issue tracker.

I installed `ember-cli-dialog`, build my project, and immediately I get the following error in my console:
```
Error: Cannot call `compile` without the template compiler loaded. Please load `ember-template-compiler.js` prior to calling `compile`.
```

And no modules can be loaded (it's broken). There is no way to use this project!

The above is using `ember install ember-cli-dialog` and it installed version `0.0.6`.

I then tried against the latest commit in `ember-cli-dialog beta1` and the latest commit in `ember-dialog beta`. With this configuration, there is no immediate error, but this error comes up as soon as I call `this.get('dialogManager').confirm(message)`:
```
Error: You have to include `ember-template-compiler.js` file to compile templates on fly. If you don't want to, you should provide a view instead or template name.
```

**Comment by ajile** [comment]
You were right when decide install `beta` version.

The text that you send into `confirm` method, processes as a view. The error appears when you trying to compile a view on fly (all Ember templates should be precompiled).

To avoid this error you should create a template, and use its name to show a modal window.

--

Template (`templates/modals/delete-user.hbs`):
```hbs
Do you really want to delete user {{model.username}}?
```

Controller (`controllers/users.js`):
```es6
export default Ember.Controller.extend({
  action: () => {
    const promise = this.get('dialogManager').confirm("modals/delete-user", this);
    promise.then(() => this.get("model").deleteRecord());
  }
});
```

--

Or there is another solution - include `ember-template-compiler.js` into project to compile a text on fly.

Controller (`controllers/users.js`):
```es6
export default Ember.Controller.extend({
  action: () => {
    const message = "Do you really want to delete user {{model.username}}?";
    const promise = this.get('dialogManager').confirm(message, this);
    promise.then(() => this.get("model").deleteRecord());
  }
});
```

Please look at the http://emberjs.com/blog/2015/02/05/compiling-templates-in-1-10-0.html#toc_client-side-compilation.

--

I'm not sure, but believe there is third way - is use `ember-cli-htmlbars-inline-precompile`.

Controller (`controllers/users.js`):
```es6
import hbs from 'htmlbars-inline-precompile';

export default Ember.Controller.extend({
  action: () => {
    const message = hbs`Do you really want to delete user {{model.username}}?`;
    const promise = this.get('dialogManager').confirm(message, this);
    promise.then(() => this.get("model").deleteRecord());
  }
});
```

See https://github.com/pangratz/ember-cli-htmlbars-inline-precompile
