### ISSUE TITLE
Fix addon to work with ember 2.10.0 and above

### ISSUE THREAD

**Issue by ajile** [wheely/ember-dialog#87]
I've ran into the problem of using `ember-dialog` with `ember@v2.10.0`. Seems the Ember Component does not have `template` property anymore, and the dialogs show up without body. While with the previous version of `ember@v2.9.1` it works fine.

You may reproduce the problem so:

app/components/foo-bar.js
```es6
import Ember from "ember";
import hbs from 'htmlbars-inline-precompile';

Ember.Component.extend({
  template: hbs`A TEMPLATE`
})
```

app/components/foo-bar.hbs
```hbs
BEGIN {{yield}} END
```

Ember v2.9.1 will output: `BEGIN A TEMPLATE END`, but Ember v2.10.10 will output: `BEGIN  END`

**Comment by waleedq** [comment]
I've created a new issue regarding the template property in ember.js here is a link for that https://github.com/emberjs/ember.js/issues/14713, let's see what API changes that caused this issue.
