### ISSUE TITLE
Doesn't work with ember-cli 2.13

### ISSUE THREAD

**Issue by treelite** [wheely/ember-dialog#93]
Hi,

I'm upgrading `ember-cli` to 2.13, but it seems that `ember-dialog` does't work with the latest version of `ember-cli`, there is an error:

```sh
ember-cli-htmlbars-inline-precompile@0.3 requires the host to use ember-cli-babel@5. To use ember-cli-babel@6 please upgrade ember-cli-htmlbars-inline-precompile to 0.4.
```

The `ember-cli-htmlbars-inline-precompile`is conflicted. I saw the `package.json` has been  updated and fixed this issue, would you mind to publish this change?

**Comment by ajile** [comment]
Thank you for your notice. I'm already prepared pull request that fixes the problem. Tomorrow I'm going to release it under `v3.1.0` version.

**Comment by treelite** [comment]
So cool, can't wait to upgrade, thanks ~
