### ISSUE TITLE
Documentation about testing

### ISSUE THREAD

**Issue by lesyk-lesyk** [wheely/ember-dialog#96]
Do you have documentation how to test component/controllers which use your dialog service?
And also do you have documentation how to test a templates/component/forms inside a dialog?
Can you provide some test helpers for integration and acceptance tests?

**Comment by ajile** [comment]
For now the `ember-dialog` does not have testing documentation, neither test helpers. I'm going to create these soon, but actually don't know when.

If you will created some of them, please send me pull request, I'll accept it.
